Api method to get live updates by id
reddit/reddit-plugin-liveupdate pull request #151
Opened 2016-12-21 22:07 UTC by dkasper

This will allow us to efficiently fetch multiple live events at a time from the gateway for displaying in carousels or banners.

2016-12-21 22:07 UTC, dkasper commented
👓  @spladug

2016-12-21 23:45 UTC, spladug commented on reddit_liveupdate/validators.py
> +                self.param: ("A comma-separated list of ids")
nit: trailing comma please

2016-12-21 23:48 UTC, spladug requested changes
looks good! just some tiny nits. for the commit message, can you follow the standard and make it an instruction like "Add API Method ... " please?

2016-12-21 23:48 UTC, spladug commented on reddit_liveupdate/validators.py
> +                self.param: ("A live update event id")
nit: trailing comma please

2017-01-13 21:00 UTC, dkasper commented
:haircut_man:

2017-01-13 21:01 UTC, spladug approved these changes

2017-01-17 18:10 UTC, closed without merging